#!/bin/bash

while [ -n "$1" ]
do
	case "$1" in
	-n)
		n=$2
		shift 2
		;;
	-t)
		t=$2
		shift 2
		;;
	--)
		text=$2
		shift 2
		;;
	*) 
		break
		;;
	esac
done

i=1
echo $text
while [ $i -lt $n ]
do
	sleep $t
	echo $text
	i=$(( $i + 1 ))
done

