#!/bin/bash

myprinter() {
str=$1
[[ $str == *\* ]] && str="${str::-1}"
if [[ "$str" == */ ]]
then 
echo '*'
else
IFS='/'
arr=($str)
unset IFS
x=${#arr[*]}
z=${arr[$(( $x - 1 ))]}
echo $z
fi
}

files() {
if [ -n "$2" ]
	then
	n=$2
	else
	n=1
fi
for file in $1/*
do
	#echo $file
	temp=$( myprinter $file )
	echo "$n)$temp"
	if [ -d "$file" ]
	then 
	n=$(( $n + 1 ))
	files "$file" $n
	n=$(( $n - 1 ))
	fi
done
}
files $1 

